### ISSUE TITLE
Getting errors on homography training

### ISSUE THREAD

**Issue by xue-zzx-zhang** [fkluger/consac#7] opened 2022-05-19 20:45 UTC
Hi, I am getting an error message when I trying to train the homography model.  Could you help?

The command that I used is circled in the screenshot as bellow. 

![error](https://user-images.githubusercontent.com/100447049/169401598-4252e43c-5d63-4871-a114-0834ece02fc4.JPG)

**Comment by fkluger** [comment] 2022-06-10 10:15
Duplicate of #8

**Closed as completed by fkluger** 2022-06-10 10:15 UTC
